apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: go-demo-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
    - hosts:
        - jcostabe.evilcorp.com
      secretName: go-demo-tls-cert
  rules:
  - host: jcostabe.evilcorp.com
    http:
      paths:
      - path: "/*"
        backend:
          serviceName: go-demo-svc
          servicePort: 8080

