apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: go-demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: jcostabe.evilcorp.com
    http:
      paths:
      - path: /
        backend:
          serviceName: go-demo-svc
          servicePort: 8080

